name: Pull Request
on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  checks: write # Allow Trunk to post annotations
  contents: read # Allow checkout
  pull-requests: write # Allow commenting on PRs

jobs:
  trunk_check:
    name: Trunk Code Quality Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate blame

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Trunk Code Quality (Formatter)
        uses: trunk-io/trunk-action@v1.2.4
        with:
          arguments: --fix --filter=formatter
          post-annotations: true # Post annotations to the PR

      - name: Trunk Code Quality (Linter)
        uses: trunk-io/trunk-action@v1.2.4
        with:
          arguments: --fix --filter=linter
          post-annotations: true # Post annotations to the PR

  build_check:
    name: Build Check
    runs-on: ubuntu-latest
    needs: trunk_check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build with Vite
        run: bun run build

      - name: Type check (if using TypeScript)
        run: |
          if [ -f "tsconfig.json" ]; then
            bun run type-check || echo "No type-check script found"
          fi
